"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g*+ajxojt5!+qm6wj%=5z4y%*$fgh9&xd@rzc^c=sq)pq9b!)c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['14.224.210.210', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['http://14.224.210.210:8088']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'suoi_tien',
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'suoitien',
        'USER': 'django_user',
        'PASSWORD': 'django_pass_2026',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'public_html' / 'halink-content' / 'uploads'

UNFOLD = {
    "SITE_TITLE": "Hệ thống Quản trị Suối Tiên",
    "SITE_HEADER": "Suối Tiên CMS",
    "SITE_SYMBOL": "park",
    "SHOW_HISTORY": True,
    "SHOW_SIDEBAR_FILTER": True,
    "DASHBOARD_CALLBACK": "suoi_tien.dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Hệ thống chung",
                "items": [
                    {
                        "title": "Bảng tin",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": "Trang chủ",
                        "icon": "home",
                        "link": "/admin/suoi_tien/halinkwebsite/",
                    },
                ],
            },
            {
                "title": "Quản lý Nội dung",
                "items": [
                    {
                        "title": "Bài viết",
                        "icon": "article",
                        "link": "/admin/suoi_tien/postproxy/",
                    },
                    {
                        "title": "Chuyên mục",
                        "icon": "category",
                        "link": "/admin/suoi_tien/postcategoryproxy/",
                    },
                    {
                        "title": "Thư viện",
                        "icon": "photo_library",
                        "link": "/admin/suoi_tien/halinkflash/",
                    },
                    {
                        "title": "Trang",
                        "icon": "description",
                        "link": "/admin/suoi_tien/pageproxy/",
                    },
                    {
                        "title": "Sản phẩm/Món ăn",
                        "icon": "restaurant",
                        "link": "/admin/suoi_tien/productproxy/",
                    },
                    {
                        "title": "Danh mục sản phẩm",
                        "icon": "folder",
                        "link": "/admin/suoi_tien/productcategoryproxy/",
                    },
                ],
            },
            {
                "title": "Tương tác & Bán hàng",
                "items": [
                    {
                        "title": "Bình luận",
                        "icon": "comment",
                        "link": "/admin/suoi_tien/commentproxy/",
                    },
                    {
                        "title": "Hỗ trợ",
                        "icon": "support_agent",
                        "link": "/admin/suoi_tien/supportproxy/",
                    },
                    {
                        "title": "Đơn hàng",
                        "icon": "shopping_cart",
                        "link": "/admin/suoi_tien/ticketorderproxy/",
                    },
                    {
                        "title": "Đơn đặt món",
                        "icon": "receipt_long",
                        "link": "/admin/suoi_tien/foodorderproxy/",
                    },
                ],
            },
            {
                "title": "Quản trị & Cài đặt",
                "items": [
                    {
                        "title": "Thống kê",
                        "icon": "bar_chart",
                        "link": "/admin/suoi_tien/halinkstatistic/",
                    },
                    {
                        "title": "Thành viên",
                        "icon": "group",
                        "link": "/admin/suoi_tien/halinkuser/",
                    },
                    {
                        "title": "Giao diện (Themes)",
                        "icon": "palette",
                        "link": "/admin/suoi_tien/themes/",
                    },
                    {
                        "title": "Quản lý Widgets",
                        "icon": "widgets",
                        "link": "/admin/suoi_tien/widgets/",
                    },
                    {
                        "title": "Quản lý Menu",
                        "icon": "menu",
                        "link": "/admin/suoi_tien/halinkmenu/",
                    },
                    {
                        "title": "Quản trị viên",
                        "icon": "admin_panel_settings",
                        "link": "/admin/suoi_tien/halinkadmin/",
                    },
                    {
                        "title": "Cài đặt",
                        "icon": "settings",
                        "link": "/admin/suoi_tien/halinkwebsite/",
                    },
                ],
            },
        ]
    },
}

