"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g*+ajxojt5!+qm6wj%=5z4y%*$fgh9&xd@rzc^c=sq)pq9b!)c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['14.224.210.210', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['http://14.224.210.210:8088']


# Application definition

INSTALLED_APPS = [
    'unfold',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'corsheaders',
    'suoi_tien',
    'rest_framework',
    'drf_spectacular',
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Danh sách domain Frontend được phép gọi API bằng CORS.
# Khai báo qua biến môi trường CORS_ALLOWED_ORIGINS (phân tách bằng dấu phẩy),
# luôn có sẵn localhost cho môi trường phát triển.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'https://suoitien.vercel.app,http://localhost:3000'
    ).split(',')
    if origin.strip()
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# CẤU HÌNH DATABASE LOCAL (MÁY CÁ NHÂN - ĐANG TẮT ĐỂ ĐẨY LÊN SERVER)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'suoi_tien_db_v2',
#         'USER': 'root',
#         'PASSWORD': 'huydev',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         }
#     }
# }

# CẤU HÌNH DATABASE DEPLOY (SERVER CHẠY - ĐANG BẬT)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'suoitien'),
        'USER': os.environ.get('DB_USER', 'django_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'django_pass_2026'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

UNFOLD = {
    "SITE_TITLE": "Hệ thống Quản trị Suối Tiên",
    "SITE_HEADER": "Suối Tiên CMS",
    "SITE_SYMBOL": "park",
    "SHOW_HISTORY": True,
    "SHOW_SIDEBAR_FILTER": True,
    "DASHBOARD_CALLBACK": "suoi_tien.dashboard.dashboard_callback",
    "SCRIPTS": ["suoi_tien.dashboard.get_prevent_double_submit_script"],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Hệ thống chung",
                "items": [
                    {
                        "title": "Bảng tin",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                    {
                        "title": "Trang chủ",
                        "icon": "home",
                        "link": "https://suoitien.vn/",
                        # Link ngoài (FE site) có path là "/" -> Unfold so khớp "active" bằng kiểu
                        # "path in request.path" nên "/" luôn khớp với MỌI trang admin. Ép cứng False
                        # để mục này không bị sáng nhầm khi đang ở trang khác (vd: Cài đặt).
                        "active": False,
                    },
                ],
            },
            {
                "title": "Quản lý Nội dung",
                "items": [
                    {
                        "title": "Bài viết",
                        "icon": "article",
                        "link": "/admin/suoi_tien/postproxy/",
                    },
                    {
                        "title": "Chuyên mục bài viết",
                        "icon": "category",
                        "link": "/admin/suoi_tien/postcategoryproxy/",
                    },
                    {
                        "title": "Thư viện",
                        "icon": "photo_library",
                        "link": "/admin/suoi_tien/halinkflash/",
                    },
                    {
                        "title": "Trang",
                        "icon": "description",
                        "link": "/admin/suoi_tien/pageproxy/",
                    },
                    {
                        "title": "Sản phẩm/Món ăn",
                        "icon": "restaurant",
                        "link": "/admin/suoi_tien/productproxy/",
                    },
                    {
                        "title": "Danh mục sản phẩm",
                        "icon": "folder",
                        "link": "/admin/suoi_tien/productcategoryproxy/",
                    },
                ],
            },
            {
                "title": "Tương tác & Bán hàng",
                "items": [
                    {
                        "title": "Bình luận",
                        "icon": "comment",
                        "link": "/admin/suoi_tien/commentproxy/",
                    },
                    {
                        "title": "Hỗ trợ",
                        "icon": "support_agent",
                        "link": "/admin/suoi_tien/supportproxy/",
                    },
                    {
                        "title": "Đơn hàng",
                        "icon": "shopping_cart",
                        "link": "/admin/suoi_tien/ticketorderproxy/",
                    },
                    {
                        "title": "Đơn đặt món",
                        "icon": "receipt_long",
                        "link": "/admin/suoi_tien/foodorderproxy/",
                    },
                ],
            },
            {
                "title": "Quản trị & Cài đặt",
                "items": [
                    {
                        "title": "Thống kê",
                        "icon": "bar_chart",
                        "link": "/admin/suoi_tien/halinkstatistic/",
                    },
                    {
                        "title": "Thành viên",
                        "icon": "group",
                        "link": "/admin/suoi_tien/halinkuser/",
                    },
                    {
                        "title": "Giao diện (Themes)",
                        "icon": "palette",
                        "link": "/admin/suoi_tien/themes/",
                    },
                    {
                        "title": "Cấu hình Trang chủ",
                        "icon": "home_app_logo",
                        "link": "/admin/suoi_tien/home-sections/",
                    },
                    {
                        "title": "Quản lý Widgets (Footer/Tab)",
                        "icon": "widgets",
                        "link": "/admin/suoi_tien/widgets/",
                    },
                    {
                        "title": "Quản lý Menu",
                        "icon": "menu",
                        "link": "/admin/suoi_tien/halinkmenu/",
                    },
                    {
                        "title": "Quản trị viên",
                        "icon": "admin_panel_settings",
                        "link": "/admin/suoi_tien/halinkadmin/",
                    },
                    {
                        "title": "Cài đặt",
                        "icon": "settings",
                        "link": "/admin/suoi_tien/halinkwebsite/1/change/",
                    },
                ],
            },
        ]
    },
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Cho phép Admin đã đăng nhập session /admin/ (cùng trình duyệt) xem
        # trực tiếp Swagger Admin (/api/schema/swagger-ui/) mà không cần tự
        # tay đính kèm JWT Bearer token.
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'public_write': '20/min',
        'public_auth': '10/min',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Suối Tiên CMS API',
    'DESCRIPTION': 'Hệ thống API quản trị tích hợp JWT Token của Suối Tiên CMS',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'SECURITY': [
        {
            'BearerAuth': [],
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Nhập JWT Token theo định dạng: Bearer <token>',
            }
        }
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

