# Generated by Django 6.0.6 on 2026-06-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suoi_tien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkmeta',),
        ),
        migrations.CreateModel(
            name='LanguageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Ngôn ngữ',
                'verbose_name_plural': 'Ngôn ngữ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkmeta',),
        ),
        migrations.CreateModel(
            name='PostCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Chuyên mục bài viết',
                'verbose_name_plural': 'Chuyên mục bài viết',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkpost',),
        ),
        migrations.CreateModel(
            name='ProductCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Chuyên mục sản phẩm',
                'verbose_name_plural': 'Chuyên mục sản phẩm',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkpost',),
        ),
        migrations.CreateModel(
            name='SMTPProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cấu hình SMTP',
                'verbose_name_plural': 'Cấu hình SMTP',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkmeta',),
        ),
        migrations.CreateModel(
            name='SupportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Hỗ trợ',
                'verbose_name_plural': 'Hỗ trợ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suoi_tien.halinkmeta',),
        ),
        migrations.AlterModelOptions(
            name='foodorderproxy',
            options={'verbose_name': 'Đơn đặt món', 'verbose_name_plural': 'Đơn đặt món'},
        ),
        migrations.AlterModelOptions(
            name='pageproxy',
            options={'verbose_name': 'Trang tĩnh', 'verbose_name_plural': 'Trang tĩnh'},
        ),
        migrations.AlterModelOptions(
            name='postproxy',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': 'Tất cả bài viết'},
        ),
        migrations.AlterModelOptions(
            name='productproxy',
            options={'verbose_name': 'Sản phẩm/Món ăn', 'verbose_name_plural': 'Sản phẩm/Món ăn'},
        ),
        migrations.AlterModelOptions(
            name='ticketorderproxy',
            options={'verbose_name': 'Đơn hàng (Vé)', 'verbose_name_plural': 'Đơn hàng (Vé)'},
        ),
    ]
