# Generated by Django 6.0.3 on 2026-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suoi_tien', '0002_commentproxy_languageproxy_postcategoryproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halinkadmin',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='idcat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mã danh mục quản lý'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cấp độ'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='halinkadmin',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài khoản'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='date',
            field=models.DateTimeField(verbose_name='Thời gian đặt'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='dateoforg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ngày tham quan'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số tiền giảm giá'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='id_cart',
            field=models.TextField(verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='id_user',
            field=models.TextField(blank=True, null=True, verbose_name='ID người dùng'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='info_product',
            field=models.TextField(verbose_name='Thông tin vé đặt'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='info_user',
            field=models.TextField(verbose_name='Thông tin khách hàng'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='note_for_user',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú phản hồi cho khách'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='status',
            field=models.IntegerField(verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='ticlock',
            field=models.IntegerField(verbose_name='Khóa đơn hàng'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='total_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tổng tiền gốc'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='total_price_final',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tổng tiền cuối cùng'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='type_payment',
            field=models.IntegerField(verbose_name='Hình thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='halinkcart',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='halinkflash',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkflash',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='halinkflash',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chiều cao (px)'),
        ),
        migrations.AlterField(
            model_name='halinkflash',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chiều rộng (px)'),
        ),
        migrations.AlterField(
            model_name='halinkmenu',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkmenu',
            name='content_menu',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung/Liên kết Menu'),
        ),
        migrations.AlterField(
            model_name='halinkmenu',
            name='id_cat',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID danh mục gốc'),
        ),
        migrations.AlterField(
            model_name='halinkmenu',
            name='ticlock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ẩn / Hiện'),
        ),
        migrations.AlterField(
            model_name='halinkmenu',
            name='title_cat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề Menu'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='Id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='Id_post',
            field=models.IntegerField(blank=True, db_column='Id_post', null=True, verbose_name='Mã liên kết'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='meta_like',
            field=models.TextField(blank=True, null=True, verbose_name='Tổng tiền / Lượt thích'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='meta_title',
            field=models.TextField(blank=True, null=True, verbose_name='Từ khóa Meta'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='meta_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại Meta'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='meta_value',
            field=models.TextField(blank=True, null=True, verbose_name='Giá trị Meta (JSON/Nội dung)'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='meta_value_cus',
            field=models.TextField(blank=True, null=True, verbose_name='Thông tin khách hàng (JSON)'),
        ),
        migrations.AlterField(
            model_name='halinkmeta',
            name='ticlock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trạng thái khóa / Duyệt'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn tĩnh'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='fullwidth',
            field=models.IntegerField(default=1, verbose_name='Hiển thị tràn màn hình (Fullwidth)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hiển thị trang chủ / Nổi bật'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='id_user',
            field=models.IntegerField(default=1, verbose_name='ID người viết'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='idcat',
            field=models.TextField(blank=True, null=True, verbose_name='Danh mục/Chuyên mục'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả SEO (Meta Description)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Từ khóa SEO (Meta Keyword)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề SEO (Meta Title)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_banner',
            field=models.TextField(blank=True, null=True, verbose_name='Ảnh Banner'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_gallery',
            field=models.TextField(blank=True, null=True, verbose_name='Bộ sưu tập ảnh'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_sidebar',
            field=models.TextField(blank=True, null=True, verbose_name='Thanh bên (Sidebar)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Từ khóa (Tags)'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại bài viết'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_type_show',
            field=models.IntegerField(blank=True, null=True, verbose_name='Loại hiển thị'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='post_views',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='schema_org',
            field=models.TextField(blank=True, null=True, verbose_name='Cấu trúc Schema JSON-LD'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự sắp xếp'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='ticlock',
            field=models.CharField(default='0', max_length=1, verbose_name='Ẩn / Hiện'),
        ),
        migrations.AlterField(
            model_name='halinkpost',
            name='title_vn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='birthday',
            field=models.TextField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='gioitinh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='ticlock',
            field=models.IntegerField(default=0, verbose_name='Trạng thái khóa (Ẩn/Hiện)'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='type_login',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Hình thức đăng nhập'),
        ),
        migrations.AlterField(
            model_name='halinkuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tài khoản'),
        ),
    ]
